import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart'; // This file is automatically generated when you set up Firebase using the FlutterFire CLI
import 'screens/home_screen.dart';
import 'screens/sign_in_screen.dart';
import 'screens/sign_up_screen.dart';
import 'screens/dashboard_screen.dart';
import 'screens/control_screen.dart';
import 'screens/profile_screen.dart';
import 'screens/about_screen.dart';
import 'mqtt.dart'; // Import the MQTTService class here

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  final MQTTService mqttService =
      MQTTService(); // This should now be recognized

  MyApp({super.key}) {
    mqttService.connect();
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Smart Garage IoT',
      theme: ThemeData(
        brightness: Brightness.dark,
        primaryColor: Colors.blueGrey[900],
        colorScheme: ColorScheme.fromSeed(
          seedColor: Colors.deepOrange,
          brightness: Brightness.dark,
        ),
      ),
      initialRoute: '/',
      routes: {
        '/': (context) => HomeScreen(mqttService: mqttService),
        '/signin': (context) => const SignInScreen(),
        '/signup': (context) => const SignUpScreen(),
        '/dashboard': (context) => DashboardScreen(mqttService: mqttService),
        '/control': (context) => ControlScreen(mqttService: mqttService),
        '/profile': (context) => const ProfileScreen(),
        '/about': (context) => const AboutScreen(),
      },
    );
  }
}
